services:
  server:
    build:
      context: ./server
    image: habitrace-server:1.0.0
    container_name: habitrace-server
    environment:
      - PORT=4000
      - DB_PATH=/data/habitrace.db
    volumes:
      - server-data:/data
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
  client:
    build:
      context: ./client
    image: habitrace-client:1.0.0
    container_name: habitrace-client
    depends_on:
      server:
        condition: service_started
    ports:
      - "8080:80"
volumes:
  server-data:
